### ISSUE TITLE
template notice needs removal

### ISSUE THREAD

**Issue by ilessing** [UCSBCarpentry/2019-02-21-UCSBLibrary#1]
at https://ucsbcarpentry.github.io/2019-02-22-UCSBLibrary/
you can still read the template message.

**Comment by ilessing** [comment]
we changed the repo name and thus the URL to:
https://ucsbcarpentry.github.io/2019-02-21-UCSBLibrary/

@dwangywu is going to fix this one.

**Comment by ilessing** [comment]
I think this is fixed.  

@dwangywu Can you confirm you already fixed this?

**Comment by dwangywu** [comment]
yes.

Ian Lessing <notifications@github.com> 于 2019年2月19日 周二 16:13写道：
