### ISSUE TITLE
Images!

### ISSUE THREAD

**Issue by jonjab** [UCSBCarpentry/2019-02-21-UCSBLibrary#3]
many images are not appearing in the episodes for this workshops.  

I started fixing the git lesson by changing paths from ../fig/... to fig/...

**Comment by ilessing** [comment]
I did some work on this last night and got some of them fixed.
I think all the image files should go in `2019-02-21-UCSBLibrary/fig/`
and then all the markdown files such as `_episodes/git-novice/01-basic.md` should be adjusted to point their linked images to their specific images in the `2019-02-21-UCSBLibrary/fig/` folder

**Comment by ilessing** [comment]
@jonjab @fishymary @sharonwsolis @dwangywu @gjanee 
I think I have all the image linking issues fixed but I would love for you all to test and verify for your selves.

**Comment by ilessing** [comment]
I think we're good on this one.
